services:
  catalog-service:
    image: "catalog-service:0.0.1-SNAPSHOT"
    container_name: "catalog-service"
    ports:
      - 8080:8080
      # - 8001:8001
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/catalog
      # - BPL_DEBUG_ENABLED=true 
      # - BPL_DEBUG_PORT=8001
